name: actions-test-workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
      
      - name: Create local changes
        run: |
          date > testfile 
          echo "my test" >> testfile
          pwd >> testfile 
          echo $HOME >> testfile 
          env >> testfile 
      - name: run a shell script 
        run: |
          chmod u+x ./scripts/run.sh 
          ./scripts/run.sh 
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Run a node.js script 
        uses: jmetzger/actions-test@master
        
